[project]
name = "class-03"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "great-expectations>=1.7.1",
    "pandas>=2.3.3",
]
